-- Migration: QR Code Onboarding System
-- Description: Add tables for QR code based employee onboarding with initial skill assessment

-- Table: onboarding_qr_codes
-- Stores QR codes generated by admins for employee onboarding
CREATE TABLE IF NOT EXISTS onboarding_qr_codes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code VARCHAR(255) UNIQUE NOT NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT true,
  max_uses INTEGER DEFAULT NULL, -- NULL means unlimited
  current_uses INTEGER DEFAULT 0,
  description TEXT, -- Optional description for tracking (e.g., "Training session March 2025")
  CONSTRAINT valid_expiration CHECK (expires_at IS NULL OR expires_at > created_at)
);

-- Table: onboarding_assessments
-- Stores initial assessment questions for new employees
CREATE TABLE IF NOT EXISTS onboarding_assessments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  questions JSONB NOT NULL, -- Array of questions with structure: [{question: string, options: string[], correct: number}]
  target_roles JSONB, -- Array of job roles this assessment is for (null = all roles)
  is_active BOOLEAN DEFAULT true,
  passing_score INTEGER DEFAULT 70, -- Percentage needed to pass
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: onboarding_responses
-- Stores employee responses to initial assessments
CREATE TABLE IF NOT EXISTS onboarding_responses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  assessment_id UUID REFERENCES onboarding_assessments(id) ON DELETE CASCADE,
  qr_code_id UUID REFERENCES onboarding_qr_codes(id) ON DELETE SET NULL,
  answers JSONB NOT NULL, -- Array of selected answer indices
  score INTEGER NOT NULL, -- Percentage score
  passed BOOLEAN NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, assessment_id)
);

-- Add initial assessment score to user_profiles
ALTER TABLE user_profiles
ADD COLUMN IF NOT EXISTS initial_assessment_score INTEGER,
ADD COLUMN IF NOT EXISTS initial_assessment_completed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS onboarded_via_qr BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS birth_date DATE;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_qr_codes_active ON onboarding_qr_codes(is_active, expires_at);
CREATE INDEX IF NOT EXISTS idx_qr_codes_code ON onboarding_qr_codes(code) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_assessments_active ON onboarding_assessments(is_active);
CREATE INDEX IF NOT EXISTS idx_responses_user ON onboarding_responses(user_id);
CREATE INDEX IF NOT EXISTS idx_responses_assessment ON onboarding_responses(assessment_id);

-- Function to check if QR code is still valid
CREATE OR REPLACE FUNCTION is_qr_code_valid(qr_code_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  qr_record RECORD;
BEGIN
  SELECT is_active, expires_at, max_uses, current_uses
  INTO qr_record
  FROM onboarding_qr_codes
  WHERE id = qr_code_id;

  IF NOT FOUND THEN
    RETURN FALSE;
  END IF;

  -- Check if active
  IF NOT qr_record.is_active THEN
    RETURN FALSE;
  END IF;

  -- Check expiration
  IF qr_record.expires_at IS NOT NULL AND qr_record.expires_at < NOW() THEN
    RETURN FALSE;
  END IF;

  -- Check max uses
  IF qr_record.max_uses IS NOT NULL AND qr_record.current_uses >= qr_record.max_uses THEN
    RETURN FALSE;
  END IF;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- Function to increment QR code usage
CREATE OR REPLACE FUNCTION increment_qr_code_usage(qr_code_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE onboarding_qr_codes
  SET current_uses = current_uses + 1
  WHERE id = qr_code_id;
END;
$$ LANGUAGE plpgsql;

-- Insert a default assessment questionnaire for general onboarding
INSERT INTO onboarding_assessments (title, description, questions, is_active, passing_score)
VALUES (
  'Évaluation initiale générale',
  'Évaluation des compétences de base pour tous les nouveaux employés',
  '[
    {
      "question": "Quelle est la priorité numéro un dans le service client ?",
      "options": [
        "Vendre le plus de produits possible",
        "Assurer la satisfaction du client",
        "Terminer les tâches rapidement",
        "Respecter les procédures strictement"
      ],
      "correct": 1
    },
    {
      "question": "Comment devez-vous réagir face à un client mécontent ?",
      "options": [
        "L''ignorer et continuer votre travail",
        "Écouter activement et chercher une solution",
        "Le diriger vers quelqu''un d''autre",
        "Lui expliquer qu''il a tort"
      ],
      "correct": 1
    },
    {
      "question": "Que signifie travailler en équipe ?",
      "options": [
        "Faire son travail sans déranger les autres",
        "Collaborer et s''entraider pour atteindre les objectifs communs",
        "Suivre les ordres du manager uniquement",
        "Compétitionner avec ses collègues"
      ],
      "correct": 1
    },
    {
      "question": "En cas de doute sur une procédure, que devez-vous faire ?",
      "options": [
        "Improviser en fonction de la situation",
        "Demander conseil à votre superviseur",
        "Faire comme bon vous semble",
        "Attendre que quelqu''un vous dise quoi faire"
      ],
      "correct": 1
    },
    {
      "question": "Quelle attitude adopter face aux règles d''hygiène et de sécurité ?",
      "options": [
        "Les respecter seulement quand le manager est présent",
        "Les appliquer rigoureusement en toute circonstance",
        "Les considérer comme des suggestions",
        "Les adapter selon les situations"
      ],
      "correct": 1
    }
  ]'::jsonb,
  true,
  70
) ON CONFLICT DO NOTHING;

-- Enable Row Level Security
ALTER TABLE onboarding_qr_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_responses ENABLE ROW LEVEL SECURITY;

-- RLS Policies for onboarding_qr_codes
CREATE POLICY "Admins can manage QR codes"
  ON onboarding_qr_codes
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role = 'admin'
    )
  );

CREATE POLICY "Anyone can read active QR codes"
  ON onboarding_qr_codes
  FOR SELECT
  USING (is_active = true AND (expires_at IS NULL OR expires_at > NOW()));

-- RLS Policies for onboarding_assessments
CREATE POLICY "Admins can manage assessments"
  ON onboarding_assessments
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role = 'admin'
    )
  );

CREATE POLICY "Anyone can read active assessments"
  ON onboarding_assessments
  FOR SELECT
  USING (is_active = true);

-- RLS Policies for onboarding_responses
CREATE POLICY "Users can insert their own responses"
  ON onboarding_responses
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can read their own responses"
  ON onboarding_responses
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can read all responses"
  ON onboarding_responses
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role = 'admin'
    )
  );

-- Grant necessary permissions
GRANT ALL ON onboarding_qr_codes TO authenticated;
GRANT ALL ON onboarding_assessments TO authenticated;
GRANT ALL ON onboarding_responses TO authenticated;
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON onboarding_qr_codes TO anon;
GRANT SELECT ON onboarding_assessments TO anon;

-- Comments for documentation
COMMENT ON TABLE onboarding_qr_codes IS 'QR codes generated by admins for employee onboarding';
COMMENT ON TABLE onboarding_assessments IS 'Initial skill assessment questionnaires for new employees';
COMMENT ON TABLE onboarding_responses IS 'Employee responses to initial assessments with scores';
COMMENT ON COLUMN user_profiles.initial_assessment_score IS 'Score from the initial onboarding assessment (0-100)';
COMMENT ON COLUMN user_profiles.onboarded_via_qr IS 'Indicates if user was onboarded through QR code system';
